name: intmodel
channels:
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
# - _openmp_mutex
- attrs=21.4.0
- blas=1
- blosc=1.21.1
- boost-cpp=1.74.0
- bottleneck=1.3.5
- branca=0.5.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.6.15
- cairo=1.16.0
- certifi=2022.6.15
- cffi=1.15.1
- cfitsio=4.1.0
- charset-normalizer=2.1.0
- click=8.1.3
- click-plugins=1.1.1
- cligj=0.7.2
- cryptography=37.0.1
- curl=7.83.1
- cycler=0.11.0
- et_xmlfile=1.1.0
- expat=2.4.8
- fiona=1.8.21
- folium=0.12.1.post1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.36.0
- freetype=2.11.0
- freexl=1.0.6
- gdal=3.5.1
- geopandas=0.11.1
- geopandas-base=0.11.1
- geos=3.11.0
- geotiff=1.7.1
- gettext=0.19.8.1
- giflib=5.2.1
- hdf4=4.2.15
- hdf5=1.12.1
- icu=70.1
- idna=3.3
- iniconfig=1.1.1
- intel-openmp=2021.4.0
- jinja2=3.1.2
- joblib=1.1.0
- jpeg=9e
- json-c=0.16
- kealib=1.4.15
# - keyutils
- kiwisolver=1.4.4
- krb5=1.19.3
- lcms2=2.12
- ld_impl_linux-64
- lerc=3
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=7.83.1
- libdap4=3.20.6
- libdeflate=1.8
- libedit=3.1.20191231
- libev=4.33
- libffi=3.4.2
# - libgcc-ng
- libgdal=3.5.1
- libgfortran-ng
- libgfortran5
- libglib=2.72.1
- libiconv=1.16
- libkml=1.3.0
- liblapack=3.9.0
- libnetcdf=4.8.1
- libnghttp2=1.47.0
# - libnsl
- libpng=1.6.37
- libpq=14.5
- librttopo=1.1.0
- libspatialindex=1.9.3
- libspatialite=5.0.1
- libssh2=1.10.0
# - libstdcxx-ng
- libtiff=4.4.0
- libuuid=2.32.1
- libwebp=1.2.2
- libwebp-base=1.2.2
- libxcb=1.13
- libxml2=2.9.14
- libxslt=1.1.35
- libzip=1.9.2
- libzlib=1.2.12
- llvm-openmp=14.0.4
- lxml=4.9.1
- lz4-c=1.9.3
- mapclassify=2.4.3
- markupsafe=2.1.1
- matplotlib-base=3.5.2
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- munch=2.5.0
- munkres=1.1.4
- ncurses=6.3
- networkx=2.8.5
- nspr=4.32
- nss=3.78
- numexpr=2.8.3
- numpy=1.23.1
- numpy-base=1.23.1
- openjpeg=2.4.0
- openpyxl=3.0.9
- openssl=3.0.5
- packaging=21.3
- pandas=1.4.3
- patsy=0.5.2
- pcre=8.45
- pillow=9.2.0
- pip=22.1.2
- pixman=0.40.0
- pluggy=1.0.0
- poppler=22.04.0
- poppler-data=0.4.11
- postgresql=14.5
- proj=9.0.1
- pthread-stubs=0.4
- py=1.11.0
- pycparser=2.21
- pyopenssl=22.0.0
- pyparsing=3.0.4
- pyproj=3.3.1
- pysocks=1.7.1
- pytest=7.1.2
- python=3.10.5
- python-dateutil=2.8.2
- python-pptx=0.6.21
- python_abi
- pytz=2022.1
- readline=8.1.2
- requests=2.28.1
- rtree=1.0.0
- scikit-learn=1.1.2
- scipy=1.9.0
- seaborn=0.11.2
- seaborn-base=0.11.2
- setuptools=61.2.0
- shapely=1.8.4
- six=1.16.0
- snappy=1.1.9
- sqlite=3.39.2
- statsmodels=0.13.2
- threadpoolctl=3.1.0
- tiledb=2.9.5
- tk=8.6.12
- tomli=2.0.1
- tzcode=2022c
- tzdata=2022a
- unicodedata2=14.0.0
- urllib3=1.26.11
- wheel=0.37.1
- xerces-c=3.2.3
- xlsxwriter=3.0.3
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2022.6.0
- xz=5.2.5
- zlib=1.2.12
- zstd=1.5.2
- pip:
  - astroid==2.11.7
  - autopep8==1.6.0
  - black==22.6.0
  - dill==0.3.5.1
  - gitdb==4.0.9
  - gitpython==3.1.27
  - isort==5.10.1
  - lazy-object-proxy==1.7.1
  - mccabe==0.7.0
  - mypy-extensions==0.4.3
  - pathspec==0.9.0
  - platformdirs==2.5.2
  - pulp==2.6.0
  - pycodestyle==2.8.0
  - pylint==2.14.4
  - smmap==5.0.0
  - toml==0.10.2
  - tomlkit==0.11.1
  - wrapt==1.14.1