name: intmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - openpyxl
  - statsmodels
  - python-pptx
  - pytest
  - geopandas
  - seaborn
  - pyyaml 
  - ipykernel
  - flake8
  - plotly # consider removing, but required for animal populations currently
  - pip:
    - gitpython
    - pulp
