name: intmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - openpyxl
  - statsmodels
  - python-pptx
  - pytest
  - geopandas
  - seaborn
  - yaml
  - ipykernel
  - flake8
  - pip:
    - gitpython
    - pulp
