name: Docs

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Autogenerate new documentation
        continue-on-error: true
        run: |
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyyaml
          python automate_mkdocs.py
          git add .
      - name: Update and Build GH Pages
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.2.3
          pip install mkgendocs==0.9.0
          pip install markupsafe==2.0.1
          pip install jinja2==2.11
          gendocs --config mkgendocs.yml
      - name: deploy
        run: |
          mkdocs gh-deploy --force --clean --verbose 	    

      - name: Commit any changes to docs
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git add ./docs
          git commit -m "Auto-updating the docs"
          

      - name: Push the changes to master
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true  



